### ISSUE TITLE
please generate a release

### ISSUE THREAD

**Issue by greysAcademicCode** [smithlabcode/preseq#11]
Could you please tag one or more of your commits as a release? Maybe corresponding to points in time that you've released preseqR to CRAN.

**Comment by timydaley** [comment]
New version updated, added version number.

**Comment by greysAcademicCode** [comment]
This issue should not have been closed. There is still no release: https://github.com/smithlabcode/preseq/releases

Generating releases in Github is easy and only takes a few clicks in the web UI. It's important because helps others who use your code (like me) pick put points in time when you think the code base is suitable for general consumption.
