### ISSUE TITLE
fail to checkout smithlab_cpp

### ISSUE THREAD

**Issue by chaodengusc** [smithlabcode/preseq#12]
fatal: reference is not a tree: 0f0e9e6d71fe72104ec7242c9cf8c701df6bc69b
Unable to checkout '0f0e9e6d71fe72104ec7242c9cf8c701df6bc69b' in submodule path 'smithlab_cpp'

**Comment by pjuren** [comment]
The submodule reference points to a commit that doesn't exist in GitHub. Mostly likely reason is that somebody modified their local smithlab_cpp (generally a bad idea) and committed, but didn't push. I bumped the reference to the most recent commit to smithlab_cpp that is on GitHub, which fixes this particular issue, but the build is still broken (for me) ... somebody else can fix that.
