### ISSUE TITLE
Question regarding "Complexity challenge" (out of curiosity)

### ISSUE THREAD

**Issue by skurscheid** [smithlabcode/preseq#17]
I have had a look around the Preseq website as I am interested in implementing it as part of our ChIP-Seq workflow, and also to stimulate some discussions with lab members regarding the re-sequencing of existing ChIP libraries. I came across the complexity challenge pages, and was surprised to see the plot for the WGBS library:

http://smithlabresearch.org/wp-content/uploads/SRX314956-1.png

Is this a typical behaviour for WGBS data? It seems that it would be nearly impossible to ever reach saturation in this type of experiment...

Anyway, thanks for this tool, I think it will be very helpful in order to assess library quality prior to performing more sequencing runs.

**Comment by timydaley** [comment]
Hi Sebastian,
I'm glad you're interested in using preseq and took a look at your preseq
challenge page.  I really hope that you include it in your ChIP-seq
pipeline.  Though we developed our tool with bisulfite sequencing libraries
in mind, my experience has been that the ChIP-seq community has made the
most use of it.

Now specifically to your question, is the nice behavior shown typical of
BS-seq libraries.  Well, not really.  In our experience in using preseq on
public and private data, there really is no "typical" behavior for BS-seq
data.  Some libraries are excellent, some libraries are poor, and a lot of
libraries are variable and difficult to determine the complexity.  We have
had libraries that initially look excellent (97% duplication rate at around
~5M reads) that end up being low complexity (55% duplication rate at ~100M
reads).  And that was really why this project was started.  It is very
difficult to predict the complexity of libraries.  There are libraries with
a low number of molecule at uniform abundance that look good in shallow
sequencing and there are libraries with a large number of molecules with
highly heterogenous abundances that appear poor in shallow sequencing.
Distinguishing between the two is difficult and is part of the success of
preseq is that it is agnostic of the underlying heterogeneity in the
library while still taking it into account.

Sorry if I didn't succinctly answer your question, but this a difficult
problem with a lot to consider.  Let me know if I can clear anything up and
if you have more questions.



On Wed, Aug 19, 2015 at 9:35 PM, Sebastian Kurscheid <
notifications@github.com> wrote:

> I have had a look around the Preseq website as I am interested in
> implementing it as part of our ChIP-Seq workflow, and also to stimulate
> some discussions with lab members regarding the re-sequencing of existing
> ChIP libraries. I came across the complexity challenge pages, and was
> surprised to see the plot for the WGBS library:
>
> http://smithlabresearch.org/wp-content/uploads/SRX314956-1.png
>
> Is this a typical behaviour for WGBS data? It seems that it would be
> nearly impossible to ever reach saturation in this type of experiment...
>
> Anyway, thanks for this tool, I think it will be very helpful in order to
> assess library quality prior to performing more sequencing runs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smithlabcode/preseq/issues/17>.
>



-- 
Timothy Daley
University of Southern California

**Comment by skurscheid** [comment]
Hi Timothy,

thank you for your reply, it is very informative! I might take you up on the offer to ask a few more questions.

Cheers,

Sebastian
