### ISSUE TITLE
2.0 release tarball does not include smithlab_cpp sources

### ISSUE THREAD

**Issue by rekado** [smithlabcode/preseq#19]
The latest release tarball is not self-contained.  While it is good that `preseq` does not bundle `smithlab_cpp`, it is not easy to build `preseq` as there has not been an official release of the `smithlab_cpp` library.

Just unpacking the tarball and building preseq results in an error:

~~~
make: *** No rule to make target '/tmp/nix-build-preseq-2.0.drv-0/preseq-2.0/smithlab_cpp//smithlab_os.o', needed by 'preseq'.  Stop.
~~~

In my latest version of the preseq package for GNU Guix I'm first building a prelease of `smithlab_cpp` and then set `SMITHLAB_CPP` to the lib output of that package; I also modify the `INCLUDEDIRS` variable such that the installed headers of the `smithlab_cpp` package can be found.

If there will be a release for `smithlab_cpp` soon, it would be nicer if preseq could be linked against that library directly.

**Comment by timydaley** [comment]
I think I fixed it.  If it's not fixed, let me know.  I'm leaving this issue open until I'm sure it's fixed.
Thank you.

**Comment by greysAcademicCode** [comment]
It's not fixed.

**Comment by timydaley** [comment]
Yes, we know that GitHub doesn't include submodules on the release.  That's why I included a separate tarball (https://github.com/smithlabcode/preseq/releases/download/v2.0.2/preseq_v2.0.2.tar.bz2) that includes the submodule.
