### ISSUE TITLE
Not all `PROGS` can be built

### ISSUE THREAD

**Issue by rekado** [smithlabcode/preseq#20]
The Makefile contains this line:

    PROGS = preseq mincount_extrap mincount_c_curve saturation_extrap test_quadrature

However, there seem to be no targets to build all but preseq.  To build preseq from sources I had to set `PROGS=preseq`.  Otherwise the build would fail:

~~~
install: cannot stat ?mincount_extrap?: No such file or directory
install: cannot stat ?mincount_c_curve?: No such file or directory
install: cannot stat ?saturation_extrap?: No such file or directory
install: cannot stat ?test_quadrature?: No such file or directory
Makefile:105: recipe for target 'install' failed
make: *** [install] Error 1
~~~

None of the build rules create these four additional tools.

**Comment by timydaley** [comment]
Fixed in newest version.
