### ISSUE TITLE
BAM sorting errors

### ISSUE THREAD

**Issue by MatthewRalston** [smithlabcode/preseq#21]
I have a bam file which I have filtered and sorted using samtools. When I run c_curve in paired-end mode, the command fails, claiming that the reads are unsorted. It is clear from the line numbers below that the reads are sorted correctly by samtools.
```
>samtools view -b -f 2 -q 4 original.bam > unsorted.bam
>samtools sort unsorted.bam final
>samtools index final.bam
>echo $?
0
>preseq c_curve -s 10000 -P -B final.bam
ERROR:	reads unsorted in: final.bam
prev = 	chr1	1749306	1749357	HWI:1:X:1:2111:4871:48281	0	+
curr = 	chr1	1749275	1749326	HWI:1:X:1:2315:16167:50307	0	+
Increase seg_len if in paired end mode
>samtools view final.bam | grep -n HWI:1:X:1:2111:4871:48281
3126:HWI:1:X:1:2111:4871:48281  ... chr1	1749307 ...
3127:HWI:1:X:1:2111:4871:48281  ... chr1	1756855
>samtools view final.bam | grep -n HWI:1:X:1:2315:16167:50307
3125:HWI:1:X:1:2315:16167:50307  ...	chr1	1749276 ...
3128:HWI:1:X:1:2315:16167:50307  ...	chr1	1756860 ...
```

**Comment by timydaley** [comment]
Hi Matt,
It looks like you have paired end reads and the insert size of these two reads are longer than the segment length (seg_len).  The default is 5000 and your reads have an insert size of about 8kb.  Setting seg_len to 10000 (or even better 100000) should solve the problem.

**Comment by MatthewRalston** [comment]
Well, the curious thing is if I convert the same BAM file to bed, then run the program with bed input, the program doesnt provide the error. Why are different results provided depending on the input file format?

**Comment by timydaley** [comment]
If you convert the bam file to a mapped reads file using bam2mr and sort it by chromosome, start, and end position, then the results should be the same.  seg_len doesn't matter because the two ends don't have to be merged on the fly as they are with bam format.  If you're using another tool to convert to bed format then I can't comment on the behavior, especially if the tool doesn't merge the two ends of a read.

**Comment by MatthewRalston** [comment]
Thanks for the response, Tim. Could you clarify concerning the bed format? I used bedtools to convert the bam file to bed format (e.g. [bamtobed](http://bedtools.readthedocs.org/en/latest/content/tools/bamtobed.html) from the bedtools suite), where each alignment has its own entry in the bed file. Am I missing where you mentioned the need for merged paired reads in bed format input in the [documentation](http://smithlabresearch.org/wp-content/uploads/manual.pdf)?

**Comment by timydaley** [comment]
I don't think it's in there.  I'll look it over and make sure it's mentioned.  
Our lab and collaborators primarily use mapped read format files, which are bed files with sequence information.  See the methpipe manual at http://smithlabresearch.org/software/methpipe/ for a more thorough explanation of the mapped read format.
