### ISSUE TITLE
unable to compile master branch with gcc 5.2.0

### ISSUE THREAD

**Issue by avilella** [smithlabcode/preseq#22]
Any ideas?

```
[...]
aits<char>, std::allocator<char> >, bool, unsigned long&)'
preseq.cpp:(.text+0xa258): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, double&)'
preseq.cpp:(.text+0xa35a): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, unsigned long&)'
preseq.cpp:(.text+0xa468): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, double&)'
preseq.cpp:(.text+0xa540): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&)'
preseq.cpp:(.text+0xa609): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&)'
preseq.cpp:(.text+0xa6d2): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&)'
preseq.cpp:(.text+0xa79b): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&)'
preseq.cpp:(.text+0xa864): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&)'
preseq.cpp:(.text+0xa957): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, unsigned long&)'
preseq.cpp:(.text+0xaa2f): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&)'
preseq.cpp:(.text+0xaaaa): undefined reference to `OptionParser::parse(int, char const**, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
preseq.cpp:(.text+0xaaef): undefined reference to `_ZNK12OptionParser12help_messageB5cxx11Ev'
preseq.cpp:(.text+0xab68): undefined reference to `_ZNK12OptionParser13about_messageB5cxx11Ev'
preseq.cpp:(.text+0xabe1): undefined reference to `_ZNK12OptionParser22option_missing_messageB5cxx11Ev'
preseq.cpp:(.text+0xac5a): undefined reference to `_ZNK12OptionParser12help_messageB5cxx11Ev'
load_data_for_complexity.o: In function `load_counts_BAM_se(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<double, std::allocator<double> >&)':
load_data_for_complexity.cpp:(.text+0x7d7): undefined reference to `SAMReader::SAMReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
load_data_for_complexity.o: In function `load_counts_BAM_pe(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long&, unsigned long&, std::vector<double, std::allocator<double> >&)':
load_data_for_complexity.cpp:(.text+0x14b1): undefined reference to `SAMReader::SAMReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
load_data_for_complexity.o: In function `GenomicRegion::GenomicRegion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, char)':
load_data_for_complexity.cpp:(.text._ZN13GenomicRegionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmmS5_fc[_ZN13GenomicRegionC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmmS5_fc]+0x2f): undefined reference to `GenomicRegion::assign_chrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
load_data_for_complexity.o: In function `_ZNK13GenomicRegion9get_chromB5cxx11Ev':
load_data_for_complexity.cpp:(.text._ZNK13GenomicRegion9get_chromB5cxx11Ev[_ZNK13GenomicRegion9get_chromB5cxx11Ev]+0x20): undefined reference to `_ZN13GenomicRegion14retrieve_chromB5cxx11Ej'
collect2: error: ld returned 1 exit status
make: *** [preseq] Error 1
[rocks-av@rocks1 preseq]$ g++ --version
g++ (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by timydaley** [comment]
Oh wow.  I don't know what's going on here.  I have a couple of questions so that I can try to recreate this.
What system are you using?  
What version of preseq are you installing?  I'm pretty sure we've talked before, so are you updating?
Finally, can you send the full error output?  

Thanks Albert.

**Comment by avilella** [comment]
[err.txt](https://github.com/smithlabcode/preseq/files/145316/err.txt)
[log.txt](https://github.com/smithlabcode/preseq/files/145317/log.txt)

I now did a `git pull` on the base folder (master branch github), then also a `git pull` on the smithlab_cpp folder one level up. Then I did a `make clean` and `make 1>log.txt 2>err.txt`.

**Comment by avilella** [comment]
This is on a centos 6.2 and gcc 5.2.0

**Comment by timydaley** [comment]
Reading up on things, it looks like there are incompatibilities with C++11 and older C++ definitions of std::string (see http://stackoverflow.com/questions/34571583/understanding-gcc-5s-glibcxx-use-cxx11-abi-or-the-new-abi or http://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring).  The solution is to tell gcc you're using an older version.  
Let me talk to the lab (since this affects a lot of our code) and I'll let you know when we think we have it all fixed.
Thanks Albert.

**Comment by avilella** [comment]
Looking forward to a fix...

**Comment by timydaley** [comment]
Albert,
I apologize for the delay.  We are trying to definitively diagnose the issue.  The reason we want to be sure is that I have a suspicion that the issue has to do with the new rules about copy-on-write that is enforced with gcc 5+ (See https://meetingcpp.com/index.php/br/items/the-c-highlights-and-more-of-gcc-51.html).  Unfortunately this would effect all of the smithlab software and not just preseq.  If this is the case we don't want to just patch it up, we want to ensure our code is compliant to the latest standard.  
Sorry, you may have been the first one to have this problem but it's opening up a big can of worms on our end.  Since I have changed institutions, Chao will be taking the lead on this issue from this point on.    
Thanks Albert.

**Comment by andrewdavidsmith** [comment]
@timydaley should determine if a quick fix is possible just for @avilella and I suspect one exists. Even if this means preparing a release that has this fix, it is likely not to take too much time.

**Comment by chaodengusc** [comment]
The command "make clean" defined in makefile did not clean the .o files under the directory smithlab_cpp and samtools but only files in the preseq directory.

**Comment by timydaley** [comment]
Chao,
That doesn't sound like the issue at all.  Let's make sure Albert can compile the software before closing the issue.

**Comment by chaodengusc** [comment]
@avilella It should be fixed. Please update the preseq. Make sure you type "make clean" before you compile it. Let me know if you still fail to compile.

**Comment by saketkc** [comment]
You can apply the following patches:

https://gist.githubusercontent.com/anonymous/b41aa69282309f59bf3d/raw/fabe18e56c72d3129a7d84ebdecf5b1bbf2b3b97/preseq.patch

https://gist.githubusercontent.com/anonymous/d940bd24b7cd77699f5d/raw/70bb7dadb77a620d27cd9ea86555d7c918be4ef1/bam2mr.patch

Tested with `gcc 5.2.0`

**Comment by andrewdavidsmith** [comment]
What is this?

**Comment by andrewdavidsmith** [comment]
If by "update" you mean just pull from github, then I don't think we should assume that it should work in any case.

We should only be debugging actual releases -- and if that's what's being used, then make clean shouldn't have any effect, because it should start out clean.

**Comment by CynAro** [comment]
Was there a fix suggested for this problem?

**Comment by andrewdavidsmith** [comment]
GCC 5.2 was released in 2015, almost 5 years ago, and we will no modify the code or build system specifically to support that version of the compiler. If the same issue arises with a new compiler (e.g. GCC 8 onward) please submit a separate issue.
