### ISSUE TITLE
Unable to compile preseq in OS X El Capitain

### ISSUE THREAD

**Issue by kendomaniac** [smithlabcode/preseq#25]
Dear developers,
I am trying to install preseq in my mac.
I downloaded the preseq-master and I used make all.
I get this error:
make all
make: **\* No rule to make target `/Users/raffaelecalogero/Dropbox/calogero/delibero/single_cells/preseq-master/smithlab_cpp//smithlab_os.o', needed by`preseq'.  Stop.
could please tell me where I can get smithlab_os.o
Cheers
Raf

**Comment by andrewdavidsmith** [comment]
By “downloaded” do you mean to say cloned? If so, I think you might have needed to specify “recursive” for the clone.

Andrew

**Comment by kendomaniac** [comment]
Yes, I was meaning clone, I will do recursive
Many thanks!
cheers
Raf
----------------------------------------
Prof. Raffaele A. Calogero
Bioinformatics and Genomics Unit
MBC Centro di Biotecnologie Molecolari
Via Nizza 52, Torino 10126
Tel.   ++39 0116706457
Fax    ++39 0112366457
Mobile ++39 3333827080
email: raffaele.calogero@unito.it
       raffaele.calogero@gmail.com
www:   http://www.bioinformatica.unito.it
