### ISSUE TITLE
ERROR: Malformed line in SAM format

### ISSUE THREAD

**Issue by c-guzman** [smithlabcode/preseq#28]
Receive this error when attempting to run Preseq:

```
Command error:
  BAM_INPUT
  ERROR:	malformed line in SAM format:
  NB501293:85:HGGFMBGXY:4:12504:17802:7321 1:N:0:TGACCA	129	1 dna_sm:chromosome chromosome:GRCh37:1:1:249250621:1 REF	130060	17	1L1
```

Pair ended RNA-seq data, stranded, aligned with BBMap, sorted using Sambamba.

Any ideas?

**Comment by timydaley** [comment]
It seems like preseq doesn't like the input file, and specifically that line.  Is this the first line in the file?  What do the other lines look like?

**Comment by c-guzman** [comment]
I managed to fix the problem by sorting using Samtools instead of Sambamba. I'm receiving a different error:

```
Command error:
  BAM_INPUT
  TOTAL READS     = 1
  DISTINCT READS  = 1
  DISTINCT COUNTS = 1
  MAX COUNT       = 1
  COUNTS OF 1     = 1
  MAX TERMS       = 0
  OBSERVED COUNTS (2)
  1	1
  
  ERROR:	max count before zero is les than min required count (4), sample not sufficiently deep or duplicates removed
```

Could this be because my pipeline is downsampling my fastq files to 100k reads using reformat.sh from the BBMap suite?

**Comment by timydaley** [comment]
No, I don't think so.  It looks like preseq only thinks there's one read in the file.  That seems unlikely.  I honestly don't know what's going on here.  If you want to email me a short bam file to test, I can try to figure it out.

**Comment by c-guzman** [comment]
I can do that, what address should I send it to?

**Comment by timydaley** [comment]
Oh right.  Sorry, forgot we were communicating over github. Send it to tdaley@stanford.edu

**Comment by timydaley** [comment]
It looks like you have spaces in the read names and chromosome names.  It think this is causing a problem as the reader doesn't find the correct things in the correct place.  You can see this in SAM.cpp, that contains the modules that read sam and bam files.  On line 444:
 std::istringstream iss(str);
  if (!(iss >> name >> flag >> chrom >> start >> mapq_score >> CIGAR
        >> mate_name >> mate_start >> seg_len >> seq >> qual))
  {
    GOOD = false;
    throw SMITHLABException("malformed line in SAM format:\n" + str);
  }
The reads assumes that specific things come in a specific order according to the sam format specification: https://samtools.github.io/hts-specs/SAMv1.pdf.  I think the spaces are throwing this order off.

**Comment by c-guzman** [comment]
This may be a result of the BBMap aligner or Sambamba. Let me try using HISAT and see if I can replicate this.

**Comment by timydaley** [comment]
It also might originate in your reference and the names are just carried over, although that wouldn't explain the spaces in the read names.

**Comment by c-guzman** [comment]
I downloaded fresh Ensembl references so I haven't had them long enough to mess them up yet. This is my first time not using UCSC based references and it's been a hassle.

**Comment by timydaley** [comment]
Yeah, I think any change to a pipeline has the potential to be a hassle.

**Comment by c-guzman** [comment]
I think I generally fixed the problem, it was at the alignment level. However, i'm running into this problem:

```
Command executed:

  samtools sort -@ 30 -o Ctrl2.sortedsamtools.bam -T Ctrl2 Ctrl2.sorted.mapped.bam
  preseq lc_extrap -v -l 9000000 -P -B -o Ctrl2.ccurve.txt Ctrl2.sortedsamtools.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  PAIRED_END_BAM_INPUT
  problem merging read NB501293:85:HGGFMBGXY:3:11404:14698:17880, splitting read
  chr3	141153217	141153230	NB501293:85:HGGFMBGXY:3:11404:14698:17880	0	-	CACACAGCACACA	AAAAAEEEEEEEE	1
  chr3	192663106	192663119	NB501293:85:HGGFMBGXY:3:11404:14698:17880	0	+	GTGTGTGCTGTGT	AAAAAEEEEAE/A	1
  To merge, set max segement length (seg_len) higher.
  ERROR:	reads unsorted in: Ctrl2.sortedsamtools.bam
  prev = 	chr3	183585815	183585951	FRAG:NB501293:85:HGGFMBGXY:2:11202:14253:12951	0	+
  curr = 	chr3	141153217	141153230	NB501293:85:HGGFMBGXY:3:11404:14698:17880	0	-
  Increase seg_len if in paired end mode
```

Is it normal to have to increase the level of `-l` this much?
