### ISSUE TITLE
gc_extrap: marking duplicates and not removing them

### ISSUE THREAD

**Issue by tamaraprieto** [smithlabcode/preseq#31]
Hi, 

I was wondering whether duplicates are considered or not for estimating the library complexity when they are marked with picard but still present in the bam file.

I read in the paper that you recommend to keep duplicates ("We therefore suggest that the genome coverage is predicted with duplicated included, but note that it can also be done with duplicates removed") but not sure if the program will filter them out based on the flag.

Thanks in advance, 

Tamara

**Comment by timydaley** [comment]
They are not removed based on the flag.  You can remove them prior to preseq using samtools.


Timothy Daley

Stanford University, Departments of Statistics and Bioengineering.

________________________________

**Comment by tamaraprieto** [comment]
Thank you, I was expecting that but just wanted to be sure. 

Tamara
