### ISSUE TITLE
Unexpected complexity curves

### ISSUE THREAD

**Issue by tamaraprieto** [smithlabcode/preseq#32]
Hi, 

I was plotting complexity curves for some single-cells experiments and as you can see in the plot below, for some cases,  the total number of bases covered decreases when increasing sequencing depth. How is this possible?  

This is the command line I run:
`bam2mr -v -o ${SAMPLE}.mr ${SAMPLE}.sorted.bam
preseq gc_extrap -v -o ${SAMPLE}_inferredcov.txt ${SAMPLE}.mr`

![screen shot 2018-02-27 at 12 44 53](https://user-images.githubusercontent.com/7628968/36727032-163a4c9c-1bbc-11e8-8c92-5a4ed74e3170.png)

**Comment by andrewdavidsmith** [comment]
Reasons why this might happen:

(1) There is a bug somewhere in preseq.
(2) The initial sample is so low that the model cannot be fit (what’s the initial sample size? In nucleotides).
(3) The reads are not sorted in the required order (I do see the word “sorted” in one of your filenames).

But @timydaley isn’t there some part of the code that checks for this condition, and reports a problem fitting the model if there are positive second derivatives?

Andrew

On Feb 27, 2018, at 3:46 AM, tamaraprieto <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I was plotting complexity curves for some single-cells experiments and as you can see in the plot below, for some cases, the total number of bases covered decreases when increasing sequencing depth. How is this possible?

This is the command line I run:
bam2mr -v -o ${SAMPLE}.mr ${SAMPLE}.sorted.bam preseq gc_extrap -v -o ${SAMPLE}_inferredcov.txt ${SAMPLE}.mr

[screen shot 2018-02-27 at 12 44 53]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_7628968_36727032-2D163a4c9c-2D1bbc-2D11e8-2D8c92-2D5a4ed74e3170.png&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=2ti3K9K1XjkPszCPHB82Aw&m=a5SHq0W3wj8r32Bpu74f-hVj-OmlufInlg1iJGoq61g&s=LJdJFm5R1y6LdWLfPalhcWaFZfaANKMfsJ_g1aMszIw&e=>

**Comment by chaodengusc** [comment]
It seems like that the code still outputs the curve even if it is decreasing function. See lines 379-390 in preseq.cpp @andrewdavidsmith .

**Comment by timydaley** [comment]
I will take a look at this tomorrow morning.  Sorry, I'm booked with meetings today from 11 till 6:30.  Just want to let y'all know that I'm not ignoring this.

**Comment by timydaley** [comment]
I looked through the code and check_yield_estimates should prevent any non-increasing curves from entering into the estimates.  I'll have to check what's going on with a specific example. 
tamaraprieto, can you run preseq in VERBOSE mode, with the flag -V, and send me the output from stderr?

**Comment by tamaraprieto** [comment]
I have around 300Mb of coverage (~0.1X of human genome) for every cell. I think I don't have the last version installed in the cluster because I have been running preseq for a while. Is check_yield_estimates only in the last versions?I can install the last one and try again with the verbose mode.

**Comment by timydaley** [comment]
check_yield_estimates has been in there since the beginning, which is why I found your results strange.  Please send the stderr from just one example where the curve is decreasing.  Thank you.

**Comment by timydaley** [comment]
I particularly want the counts histogram so that I can track where the error is occuring.

**Comment by andrewdavidsmith** [comment]
Yes, @tamaraprieto you should be able to send the counts histogram by email (it will be pretty small) and it won't give away any information about your project, because in theory it could have come from any data set. Maybe the best one would be the 3rd highest curve in your original plot, which is the one that seems to have the greatest complexity, but still has the problem of predicting reduced coverage.

**Comment by tamaraprieto** [comment]
Hi all, I had repeated the analysis when it failed and output was overwritten and I don't get the same results again...which is good because now all curves look right but I don't have the files anymore to share with you. If I ever get more weird results I will let you know. Thanks for your help
