### ISSUE TITLE
Release 2.0.3?

### ISSUE THREAD

**Issue by dpryan79** [smithlabcode/preseq#35]
It looks like you've added a version 2.0.3. Can you tag that in github so the bioconda recipe can be updated? We prefer to use officially tagged releases there.

**Comment by timydaley** [comment]
Thank you Dr. Ryan for reminding me.  Please let me know if you have any issues with the new release.
By the way, thank you very much for your biostars posts.  I immediately recognized you and wanted to thank you for helping me out.  I find your posts there extremely helpful.
