### ISSUE TITLE
Problem with SAM support in preseq v2.0.3

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/preseq#38]
We have a SAM.hpp and SAM.cpp file, presumably for some wrapper, but when I try to build the code it complains about no sam.h. Is this intended behavior?

**Comment by andrewdavidsmith** [comment]
Maybe this "issue moving" worked...

**Comment by timydaley** [comment]
I think so.

**Comment by timydaley** [comment]
@KochTobi , can you type 
gsl-config --libs
to determine where your gsl libraries are and what flags you need to include?

**Comment by terencewtli** [comment]
closed because gsl is no longer needed
