### ISSUE TITLE
Question on lc_extrap input

### ISSUE THREAD

**Issue by stevenlockton-progenity** [smithlabcode/preseq#39]
For the lc_extrap function, the documentation says you can use BED or BAM as inputs. No mention of WALT mr files. But mr files seem to work just fine. So can I confirm this: Are mr files a valid input for preseq lc_extrap?

**Comment by timydaley** [comment]
From my understanding, mr files are an extension of bed files but with extra columns.  Indeed, we have a tool to convert paired end bam files to mr files, so preseq can use them. They should work just fine as long as the first columns match the bed format.
