### ISSUE TITLE
Not able to compile preseq (master)

### ISSUE THREAD

**Issue by CynAro** [smithlabcode/preseq#41]
I have tried to 'make all' the preseq directory using the gcc 8.2 compiler and gsl 2.5 but get errors. 

preseq.cpp:(.text+0x2d25): undefined reference to `strip_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/tmp/ccqhKVFD.o: In function `gc_extrap(int, char const**)':
preseq.cpp:(.text+0x540c): undefined reference to `strip_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/tmp/ccqhKVFD.o: In function `c_curve(int, char const**)':
preseq.cpp:(.text+0x7b48): undefined reference to `strip_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/tmp/ccqhKVFD.o: In function `bound_pop(int, char const**)':
preseq.cpp:(.text+0x94ef): undefined reference to `strip_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/ihome/rseal/cma83/preseq/smithlab_cpp/OptionParser.o: In function `Option::format_option_description[abi:cxx11](unsigned long, bool) const':
OptionParser.cpp:(.text+0x103b): undefined reference to `smithlab::split_whitespace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
/ihome/rseal/cma83/preseq/smithlab_cpp/OptionParser.o: In function `Option::parse_config_file(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
OptionParser.cpp:(.text+0x17fa): undefined reference to `smithlab::split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, bool)'
OptionParser.cpp:(.text+0x182d): undefined reference to `smithlab::strip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
OptionParser.cpp:(.text+0x1881): undefined reference to `smithlab::strip(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/ihome/rseal/cma83/preseq/smithlab_cpp/OptionParser.o: In function `OptionParser::about_message[abi:cxx11]() const':
OptionParser.cpp:(.text+0x3f94): undefined reference to `smithlab::split_whitespace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
/ihome/rseal/cma83/preseq/smithlab_cpp/MappedRead.o: In function `GenomicRegion::GenomicRegion()':
MappedRead.cpp:(.text._ZN13GenomicRegionC2Ev[_ZN13GenomicRegionC5Ev]+0x38): undefined reference to `GenomicRegion::assign_chrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/ihome/rseal/cma83/preseq/smithlab_cpp/MappedRead.o: In function `GenomicRegion::GenomicRegion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, float, char)':
MappedRead.cpp:(.text._ZN13GenomicRegionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmmS5_fc[_ZN13GenomicRegionC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmmS5_fc]+0x2f): undefined reference to `GenomicRegion::assign_chrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/ihome/rseal/cma83/preseq/smithlab_cpp/MappedRead.o: In function `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >& operator<< <std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >&, GenomicRegion const&)':
MappedRead.cpp:(.text._ZlsINSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEEERT_S7_RK13GenomicRegion[_ZlsINSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEEERT_S7_RK13GenomicRegion]+0x20): undefined reference to `GenomicRegion::tostring[abi:cxx11]() const'
load_data_for_complexity.o: In function `GenomicRegion::get_chrom[abi:cxx11]() const':
load_data_for_complexity.cpp:(.text._ZNK13GenomicRegion9get_chromB5cxx11Ev[_ZNK13GenomicRegion9get_chromB5cxx11Ev]+0x20): undefined reference to `GenomicRegion::retrieve_chrom[abi:cxx11](unsigned int)'
load_data_for_complexity.o: In function `std::ostream& operator<< <std::ostream>(std::ostream&, GenomicRegion const&)':
load_data_for_complexity.cpp:(.text._ZlsISoERT_S1_RK13GenomicRegion[_ZlsISoERT_S1_RK13GenomicRegion]+0x20): undefined reference to `GenomicRegion::tostring[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
make: *** [preseq] Error 1

**Comment by joshpark00** [comment]
What was your solution?

**Comment by andrewdavidsmith** [comment]
@joshpark00 feel free to reopen or open another issue if you get a different compile error message.
