### ISSUE TITLE
Installing preseq on a cluster

### ISSUE THREAD

**Issue by hugokitano** [smithlabcode/preseq#43]
Hi, I'm trying to install preseq on a cluster where I don't have the permissions to install some applications to their default location. I unzipped the tar file and found that the ./preseq executable had the following persisting error:

`preseq: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory`

I set up gsl version 1.15 (I also tried version 2.6), configuring it to a certain prefix. Still same error. I also set up `LD_LIBRARY_PATH` to point to the same location as the prefix, exported the variable, and still got the same error. 

Any ideas for why GSL isn't connecting to PreSeq? Thank you!

Hugo

**Comment by andrewdavidsmith** [comment]
This definitely looks like an issue with paths. Can you send the output from running `env` directly after attempting to run preseq (same session), and also `echo $LD_LIBRARY_PATH`. If you don't want to post all of that here, feel free to email me.

**Comment by hugokitano** [comment]
I figured it out: I needed to set LD_LIBRARY_PATH to the where I set the prefix to + "/lib".
