### ISSUE TITLE
Redundancy in setting up RNG

### ISSUE THREAD

**Issue by terencewtli** [smithlabcode/preseq#46]
This part of the code is redundant because we set the internal RNG with `srand`, but then immediately define another RNG with a pre-defined value.
```
  // setup rng
  srand(time(0) + getpid());
  std::mt19937 rng(seed);
```

**Comment by terencewtli** [comment]
Update: this still occurs all over the code (eg. line 296 in v-3.1.2). Testing to see if removing `srand` changes anything

**Comment by andrewdavidsmith** [comment]
@terencewtli Do you know the status of this?
