### ISSUE TITLE
Estimating the curve with low read count

### ISSUE THREAD

**Issue by JeffreyMaurer** [smithlabcode/preseq#49]
Hi there.

I'm trying to run preseq 3.1.1 on a new Ubuntu 20.04.1 system through the command line. I have a prepared bam file, but when I run the program, I encounter this:

```
$ preseq lc_extrap PC1-PT.bam -B -P -e 2.1e9 -s 1e8 -seg_len 1000000000 -o PC1.preseq
ERROR:  max count before zero is less than min required count (4) duplicates removed
```

Scouring the web for a solution, I look for a solution only to be met with an explanation [here](https://github.com/nugentechnologies/NuMetWG). But that doesn't appear accurate. It runs when I use a sam file as input of the same data.

I checked the help section and tried the -D option expecting some quality checks to be bypassed, but alas. Here I am. I want to know if there is any way to bypass this? I did not have this issue when working with version 2.0.3.

As an aside, and I can log this with another issue if it's a large task, one other item I noticed is that all the help pages seem to be formatted incorrectly, even the command line help. When I submit with the input file at the end of the options:

```
$ preseq lc_extrap  -B -P -e 2.1e9 -s 1e8 -seg_len 1000000000 -o PC1.preseq PC1-PT.bam
ERROR:  problem opening file: -B
```

I also did not encounter this issue in version 2.0.3.

Thanks.

**Comment by terencewtli** [comment]
Hi,

I ran both of the commands you listed with the `.bam` file in the `data` directory and it runs fine. Would it be possible for you to share your file with me so I can run some tests with it? Either way, these are some strange errors - for the first issue, I just want to confirm that you configured with the `--enable-hts` option? And for the second error, it looks like the flags are parsed incorrectly, but once again on my end, running the same command runs fine for me.

**Comment by andrewdavidsmith** [comment]
It seems there is no response after @terencewtli 's answer, so I'll close this and it can be reopened if needed.
