### ISSUE TITLE
ERROR: reads unsorted in:

### ISSUE THREAD

**Issue by didillysquat** [smithlabcode/preseq#57]
Running preseq c_curve on a paired end sorted bam gives me the following error:
```
Singularity> preseq c_curve -o out.nomerge.curve -P -B ex640_P_mapped.sorted.bam
ERROR:	reads unsorted in: ex640_P_mapped.sorted.bam
prev = 	scaffold_1	112694	112734	A00709:254:HTK7WDSX2:3:2625:13612:18865	0	+
curr = 	scaffold_1	111263	111307	A00709:254:HTK7WDSX2:3:2576:30544:8046	0	+
Increase seg_len if in paired end mode
```

c_curve runs fine if I don't use the `-P` option.

strangely, when I look into the bam, I don't see reads at the positions mentioned in the error: scaffold_1:112694 or scaffold_1:111263.

I also resorted the bam using `samtools sort` but still got the same error.

**Comment by didillysquat** [comment]
Converting to bed format first, circumnavigates this problem:

`bedtools bamtobed -i sorted.pe.bam > sorted.pe.bed`
followed by:
`preseq c_curve -P sorted.pe.bed`

**Comment by andrewdavidsmith** [comment]
@didillysquat Thanks for the question. The issue is usually the "locale" of the machine, but it seems you solved it. If you could send me by email a small portion of the file that had caused the problem, I could try to debug it. Ideally we wouldn't require you (at least for this version of the software) to convert formats. Thanks.

**Comment by didillysquat** [comment]
Hi @andrewdavidsmith . Thanks for your reply.

Long story short: c_curve is working as expected now with your v3.1.2 release that I made [a Dockerfile](https://hub.docker.com/r/didillysquat/bedtools_preseq) for.

### A little more detail that may be helpful to others:
I was originally running preseq using the v3.1.2 release via docker from [this](https://hub.docker.com/r/clinicalgenomics/preseq/tags) Docker image. Confusingly both versions of preseq report that they are running v3.1.1 so I guess this needs updating. 

Although they both claim to be either v3.1.1 or v3.1.2, they have different command line interfaces.

The most recent release I installed a couple of days ago looks like this:
```
Singularity> preseq -v
unrecognized command: -v
preseq:  a program for analyzing library complexity
Version: 3.1.1

Usage:   preseq <command> [OPTIONS]

<command>: c_curve    generate complexity curve for a library
           lc_extrap  predict the yield for future experiments
           gc_extrap  predict genome coverage low input
                      sequencing experiments
           bound_pop  lower bound on population size
           pop_size   estimate number of unique species

Singularity> preseq c_curve
Usage: c_curve [OPTIONS] <input-file>

Options:
  -o, -output   yield output file (default: stdout)  
  -s, -step     step size in extrapolations [1000000.000000] 
  -v, -verbose  print more information  
  -P, -pe       input is paired end read file  
  -H, -hist     input is a text file containing the observed histogram  
  -V, -vals     input is a text file containing only the observed 
                counts  
  -r, -seed     seed for random number generator [408] 

Help options:
  -?, -help     print this help message  
      -about    print about message
```

whereas the other version looks like this:
```
Singularity> preseq -v
unrecognized command: -v
preseq:  a program for analyzing library complexity
Version: 3.1.1

Usage:   preseq <command> [OPTIONS]

<command>: c_curve    generate complexity curve for a library
           lc_extrap  predict the yield for future experiments
           gc_extrap  predict genome coverage low input
                      sequencing experiments
           bound_pop  lower bound on population size
           pop_size   estimate number of unique species

Singularity> preseq c_curve
Usage: c_curve [OPTIONS] <input-file>

Options:
  -o, -output   yield output file (default: stdout)  
  -s, -step     step size in extrapolations [1000000.000000] 
  -v, -verbose  print more information  
  -P, -pe       input is paired end read file  
  -H, -hist     input is a text file containing the observed histogram  
  -V, -vals     input is a text file containing only the observed 
                counts  
  -B, -bam      input is in BAM format  
  -l, -seg_len  maximum segment length when merging paired end bam 
                reads [5000] 
  -r, -seed     seed for random number generator [408] 

Help options:
  -?, -help     print this help message  
      -about    print about message
```

As you can see the -B option is missing in the 'newer' version. And, it turns out that this -B option is what was causing the issue in the 'older' version. If instead of running:

`preseq c_curve -o out.nomerge.curve -P -B ex640_P_mapped.sorted.bam`

I omit the -B and run:

`preseq c_curve -o out.nomerge.curve -P ex640_P_mapped.sorted.bam`

Then the execution completes as expected with no errors reported.

So, it may be worth updating the documentation you have in the README.md to omit the -B.

Thanks again for your efforts.

All the best.
