### ISSUE TITLE
ls_extrap: too many defects, negative CI, and causes

### ISSUE THREAD

**Issue by iamTad** [smithlabcode/preseq#61]
When running lc_extrap without using defect mode (all default using input bam file), I get an error for a particular sample  stating:

> ERROR:	too many defects in the approximation, consider running in defect mode

As recommended by the manual, I've run the command in defect mode (with the -D option) and I get a negative value for the lower CI at higher total reads:

< 416000000.0 total reads, lower CI = positive
416000000.0 total reads, lower CI = 192802711.1
417000000.0 total reads, lower CI = -178785167.5
'> 417000000.0 total reads, lower CI = negative

Question 1.
I read the paper associated with this program (Predicting the molecular complexity of sequencing libraries) and don't quite understand what leads to having defects (or too many defects) in the approximation. My understanding from the supplement is that the frequencies (of each unique molecule?) affect this--but how?

Question 2.
What could be causing this negative lower CI value (and the switch from positive to negative)?

**Comment by andrewdavidsmith** [comment]
@iamTad A defect is a pole and a zero that are close enough to each other. The problem with that definition is that if a pole and zero are extremely close, then they won't ever affect what we observe as rational values representable in our computers. So we would detect smoothness. So the idea of "close enough" but also "far enough" is tricky to communicate. If I could show you a plot, you'd understand right away. It's likely some very well-performing data sets have defects that we simply can't see in their corresponding estimated rational functions. If the defects are a problem, then they could lead to predictions that are on their way to positive and negative infinity very nearby, and those would clearly fall outside whatever CI might have been estimated. On the other hand, if the defect interacted with a CI estimate, you can imagine strange things also happening. I think at one point we knew how to simulate data such that the estimated RFAs had lots of defects, and could be clearly seen. I'll take a look for those this week.

**Comment by iamTad** [comment]
I appreciate the update! This helps to clarify the questions that I initially had.
